# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Authoring
title : Oratio.io Docs
tagline: Docs for Oratio.io
author :
  name : Gabriel Tomitsuka
  email : gabriel.tomitsuka@montreus.com
  github : gtomitsuka
  

# Server
host:             0.0.0.0
port:             9001
production_url:   http://docs.oratio.io
encoding:         UTF-8

# Custom vars
current_version:  0.1.0
repo:             https://github.com/oratio-io/oratio-docs
